### ISSUE TITLE
Proxy argument causing issue with requests

### ISSUE THREAD

**Issue by lukedavoli** [kkristof200/py_bittrex_api#7]
Have just installed the package through pip. Simply trying to ping the server to make sure I have it installed correctly and that it is working. Clearly has something to do with the proxy field created and included in the request on line 139 of bittrex_requests.py. I don't have a tonne of experiences with REST APIs and requests, what is the purpose of this field?

## Expected Behavior
Status 200 OK response

## Current Behavior
`TypeError: request() got an unexpected keyword argument 'proxy'`

Full stacktrace:
```
https://api.bittrex.com/v3/ping
Traceback (most recent call last):
  File "d:/Study/Projects/Crypto_Trader/crypto_trader.py", line 3, in <module>
    print(bittrex.v3.ping())
  File "D:\Study\Projects\Crypto_Trader\venv\lib\site-packages\bittrex_api\v3.py", line 73, in ping
    return self.__request(
  File "D:\Study\Projects\Crypto_Trader\venv\lib\site-packages\bittrex_api\v3.py", line 1619, in __request
    return self.requests.request(
  File "D:\Study\Projects\Crypto_Trader\venv\lib\site-packages\bittrex_api\utils\bittrex_requests.py", line 75, in request
    self.__request(
  File "D:\Study\Projects\Crypto_Trader\venv\lib\site-packages\bittrex_api\utils\bittrex_requests.py", line 139, in __request
    resp = requests.get(url, params=params, headers=headers, proxy=proxy)
  File "D:\Study\Projects\Crypto_Trader\venv\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "D:\Study\Projects\Crypto_Trader\venv\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
TypeError: request() got an unexpected keyword argument 'proxy'
```

## Steps to Reproduce
```
from bittrex_api.bittrex import Bittrex
bittrex = Bittrex('key', 'secret', debug_level=3)
print(bittrex.v3.ping())
```

## Context
* Python 3.8.5, 64-bit
* Windows 10

**Comment by kkristof200** [comment]
Hey! Just updated the code and published it on pip. it should work now. Bittrex limits your requests to 20/minute to block scraping, the proxy field is added to avoid blocking. If you don't plan to make more than 20 request (without token), then there is no need for it.

**Comment by lukedavoli** [comment]
Thanks!
